before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-luatex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
- "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: freddiefujiwara
  - GH_PROJECT_NAME: prisma
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/prisma.pdf
  - RESULT_EPUB_PATH=$TRAVIS_BUILD_DIR/prisma.epub
  - RESULT_DOCX_PATH=$TRAVIS_BUILD_DIR/prisma.docx
  - RESULT_HTML_PATH=$TRAVIS_BUILD_DIR/index.html
  - TZ="Asia/Tokyo"
  - LANG=ja_JP.UTF8
  - secure: nX3NeulBL1MOy0xuIt5dPbuOmhnlFySwbwLRQ3l4GkFywCU/DBwl03g5c6KsSRQZKYfyJ/Hlxl8Nel0e8CAbwzlw+w9KnYRYDMTrgUFcEhttHcsFDb4/UMrmF0P/kqT7gCscDr0mdZw9SolDxAwxevYn8C6glAGN73s93ZWrIrXRLff3tJSjxWRsTjh4K0cuBcVtJbGlCl3A+lejOMn9MbKHHfGuUcGn32Ym8Tx9Z4EFvDcBSKa5qZWH3Mquk8WXdSb+Hbx2Nr11G/g1tY0SXjTQNnLQXNTbiHA52EpDIOp3XXA60CQj/jhB15jH46CWz9/0jkPY2CrR/ND/HlHMO2lTrxH6R3M156ucZVMwiM/tkMwRVjoaw+rfWJXCMp1N/qGLqJgRL4tO+6N+snjmsMdTvw1Za/HkfczbX6urKxp5zEdM098ptjd9TMIgu8oJaoLTDGagLPEkA2F8fZeDY4mMMSCtkOaHSEv39Pvq+UaDQAfvYKSwxZHWR8KS01hFjAWisIv77tv1SaKlIYCDPrm7CWJQaBUYtCclURE5+rx9PVjQfM59zNjeWqgyO8ZwRaUACAkJ7gBL8SyVHg5rponXspwyvB1gH9LzzI3OY7KeWIAhU8/89K2CNvBAr+StuTBJFKdewbyts4ioh7GuAScC2Ti5F5txiHzp9fHFEnA=
